// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:BudgetManagementSystem.BusinessLogic.Handlers.StaffMgtHandlers.GetRolePermissionQueryHandler.#ctor(BudgetManagementSystem.Infrastructure.Abstractions.IRepo{BudgetManagementSystem.Models.Core.Permission},Microsoft.AspNetCore.Identity.RoleManager{BudgetManagementSystem.Models.Core.ApplicationRole})")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:BudgetManagementSystem.BusinessLogic.Handlers.StaffMgtHandlers.GetPermissionsByRoleQueryQueryHandler.#ctor(Microsoft.AspNetCore.Identity.RoleManager{BudgetManagementSystem.Models.Core.ApplicationRole},BudgetManagementSystem.Infrastructure.Abstractions.IRepo{BudgetManagementSystem.Models.Core.Permission})")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:BudgetManagementSystem.BusinessLogic.Concretes.ReviewAgentService.#ctor(BudgetManagementSystem.Infrastructure.Concrete.ErpEmployeeService,Mediator.IMediator,BudgetManagementSystem.Infrastructure.Abstractions.IRepo{BudgetManagementSystem.Models.CompetencyMgt.CompetencyReview},BudgetManagementSystem.Infrastructure.Abstractions.IRepo{BudgetManagementSystem.Models.CompetencyMgt.CompetencyReviewProfile},BudgetManagementSystem.Infrastructure.Abstractions.IRepo{BudgetManagementSystem.Models.CompetencyMgt.CompetencyCategoryGrading})")]
[assembly: SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>", Scope = "member", Target = "~M:BudgetManagementSystem.BusinessLogic.BusinessLogicStartupExtension.AddBusinessLogicDependencies(Microsoft.Extensions.DependencyInjection.IServiceCollection)~Microsoft.Extensions.DependencyInjection.IServiceCollection")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:BudgetManagementSystem.BusinessLogic.Handlers.StaffMgtHandlers.RemovePermissionFromRoleCmdHandler.#ctor(BudgetManagementSystem.Infrastructure.Abstractions.IRepo{BudgetManagementSystem.Models.Core.RolePermission})")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:OfficeMgt.BusinessLogic.Handlers.OrganogramHandlers.SaveDepartmentHandler.#ctor(BudgetManagementSystem.Infrastructure.Abstractions.IRepo{BudgetManagementSystem.Models.Organogram.Department})")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:BudgetManagementSystem.BusinessLogic.Handlers.CompetencyMgtHandlers.GetCompetencyRatingDefinitionsHandler.#ctor(BudgetManagementSystem.Infrastructure.Abstractions.IRepo{BudgetManagementSystem.Models.CompetencyMgt.CompetencyRatingDefinition})")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:BudgetManagementSystem.BusinessLogic.Handlers.CompetencyMgtHandlers.SaveCompetencyRatingDefinitionHandler.#ctor(BudgetManagementSystem.Infrastructure.Abstractions.IRepo{BudgetManagementSystem.Models.CompetencyMgt.CompetencyRatingDefinition})")]
